name: ashic
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - click=6.7
  - iced=0.5.0
  - matplotlib=2.2.2
  - numpy=1.13.3
  - pandas=0.22.0
  - plotly=3.5.0
  - python=2.7.18
  - scikit-learn=0.19.1
  - scipy=1.0.1
  - statsmodels=0.9.0
  - pip:
    - "git+https://github.com/wmalab/ASHIC.git"